steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-south1-docker.pkg.dev/checkmate-475818/fall2025_checkmate/checkmate-app'
      - '.'

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-south1-docker.pkg.dev/checkmate-475818/fall2025_checkmate/checkmate-app'

  # Deploy to Cloud Run (correct service + region)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run','deploy','fall2025-checkmate',
        '--image','us-south1-docker.pkg.dev/checkmate-475818/fall2025_checkmate/checkmate-app',
        '--region','us-south1',
        '--platform','managed',
        '--allow-unauthenticated',
        '--set-env-vars','RAILS_ENV=production,RAILS_LOG_TO_STDOUT=true,RAILS_SERVE_STATIC_FILES=true',
        '--add-cloudsql-instances checkmate-475818:us-south1:checkmate-db'
        # If you use secrets, add: --set-secrets SECRET_KEY_BASE=secret-key-base:latest
      ]

images:
- 'us-south1-docker.pkg.dev/checkmate-475818/fall2025_checkmate/checkmate-app'

options:
  logging: CLOUD_LOGGING_ONLY