steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/spring2025-tag' 
      - '.'

  # Step 2: Push the image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/spring2025-tag' 

  # Step 3: Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'spring2025-tag'  
      - '--image'
      - 'gcr.io/$PROJECT_ID/spring2025-tag' 
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'  
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:spring2025-tag-instance' 
      - '--update-secrets'
      - 'DATABASE_PASSWORD=database-password:latest,SECRET_KEY_BASE=secret-key-base:latest'
      - '--update-env-vars'
      - 'DATABASE_HOST=/cloudsql/$PROJECT_ID:us-central1:spring2025-tag-instance,DATABASE_NAME=tagdatabase,DATABASE_USER=postgres' 

# Set build timeout (optional)
timeout: 1800s
