steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/spring2025-tag/spring2025-tag-repo/tag-app', '.']

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/spring2025-tag/spring2025-tag-repo/tag-app']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'tag-app-service',
           '--image', 'us-east1-docker.pkg.dev/spring2025-tag/spring2025-tag-repo/tag-app',
           '--region', 'us-east1']

images:
- 'us-east1-docker.pkg.dev/spring2025-tag/spring2025-tag-repo/tag-app'
