steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/spring2025-tag/spring2025-tag-repo/tag-app', '.']

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/spring2025-tag/spring2025-tag-repo/tag-app']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'tag-app-service',
        '--image', 'us-central1-docker.pkg.dev/spring2025-tag/spring2025-tag-repo/tag-app',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--add-cloudsql-instances', 'spring2025-tag:us-central1:tag-app-db',
        '--set-env-vars', 'RAILS_ENV=production,RAILS_SERVE_STATIC_FILES=true',
        '--set-secrets', 'SECRET_KEY_BASE=secret-key-base:latest,DB_PASSWORD=db-password:latest',
        '--allow-unauthenticated'
      ]

images:
- 'us-central1-docker.pkg.dev/spring2025-tag/spring2025-tag-repo/tag-app'

options:
  logging: CLOUD_LOGGING_ONLY
