version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tagdatabase

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:8080"
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_NAME: tagdatabase
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    volumes:
      - .:/app
    command: ["rails", "server", "-b", "0.0.0.0", "-p", "8080"]

volumes:
  postgres_data:
